### ISSUE TITLE
string matching operators not working as expected

### ISSUE THREAD

**Issue by conitrade-as** [cyberphor/pySigma-backend-powershell#4]
While playing with this backend we noticed that the string matching operators seem to not be working as expected. Consider the following rule `test.yml`:
```
logsource:
    category: network_connection
    product: windows
detection:
    selection:
        Image|endswith: '\wscript.exe'
        Initiated: 'true'
        DestinationPort:
            - 25
    condition: selection
```

This produces the following powershell statement:
```
$ python sigma2powershell.py -p test.yml
Get-WinEvent -LogName "None" | Read-WinEvent | Where-Object {$_.Image -like "\\wscript.exe" -and $_.Initiated -eq "true" -and $_.DestinationPort -eq 25}
```

The string matching function for `$_.Image -like "\\wscript.exe"` is not what is expected. Since there are no wildcards this never evaluates to true for sample strings like `C:\Windows\System32\wscript.exe`.

Consider this simplified case:
```
PS C:\Windows\system32> 'C:\Windows\System32\wscript.exe' -like '\wscript.exe'
False
PS C:\Windows\system32> 'C:\Windows\System32\wscript.exe' -like '*\wscript.exe'
True
```
